version: "3.9"

services:
  wa-bot:
    build: .
    container_name: wa-bot-printer
    restart: always
    network_mode: "host"
    volumes:
      - ./data:/tmp/wa-prints
      - ./auth:/app/auth
      - /etc/cups:/etc/cups  # Akses konfigurasi printer
      - /var/run/cups/cups.sock:/var/run/cups/cups.sock  # Socket komunikasi dengan printer
    environment:
      - CUPS_SERVER=192.168.0.113  # IP server printer
      - PRINTER_NAME=""  # Isi dengan nama printer yang digunakan